/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yanbing_hello_jni_Jni */

#ifndef _Included_com_yanbing_hello_jni_Jni
#define _Included_com_yanbing_hello_jni_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yanbing_hello_jni_Jni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yanbing_hello_1jni_Jni_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_yanbing_hello_jni_Jni
 * Method:    helloFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yanbing_hello_1jni_Jni_helloFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
